### ISSUE TITLE
no data fetched

### ISSUE THREAD

**Issue by nyculescu** [denolfe/jefit#1]
I tried to fetch data from Jefit and the response for 
a) jefit.fetchMostRecent() is:
{
  "exercises": []
}

b) jefit.fetchSingleDate() is:
{ exercises: [] }

So, the response is empty, even on Jefit I have a lot of data stored.

**Comment by denolfe** [comment]
It looks like they've changed a lot of the css classes that were used when I wrote this 2 years ago. I may be able to take a look soon but no guarantees. If you want to explore it yourself, take a look at the code after: https://github.com/denolfe/jefit/blob/master/lib/fetchSingleDate.js#L23. This contains classes that no longer exist and were in all likelihood just renamed to something else.

**Comment by oronbz** [comment]
Hi @nyculescu , just make sure your privacy setting is set on: **Everyone**,
this fixed it for me.

**Comment by denolfe** [comment]
Thanks @oronbz for confirming functionality! Closing.
